syntax = "proto3";

package triangel;


//services
service AuthService {
  rpc Login(LoginRequest) returns (LoginReply);
}

service DocumentConfigService {
  rpc GetDocumentConfig(DocumentConfigRequest) returns (DocumentConfigReply);
}

service DocumentsService {
  rpc GetDocuments(DocumentsRequest) returns (DocumentsReply);
}

service DocumentService {
  rpc GetDocument(DocumentRequest) returns (DocumentReply);
}

service DeleteDocumentService {
  rpc DeleteDocument(DeleteDocumentRequest) returns (DeleteDocumentReply);
}

service SendDocumentService {
  rpc SendDocument(SendDocumentRequest) returns (SendDocumentReply);
}

service TaetigkeitService {
  rpc Taetigkeit(TaetigkeitRequest) returns (TaetigkeitReply);
}

service ZeiteintraegeService {
  rpc Zeiteintraege(ZeiteintraegeRequest) returns (ZeiteintraegeReply);
}

service ZeiteintragService {
  rpc Zeiteintrag(ZeiteintragRequest) returns (ZeiteintragReply);
}

service PasswordChangeService {
  rpc PasswordChange(PasswordChangeRequest) returns (PasswordChangeReply);
}

service CreateUserService {
  rpc CreateUser(CreateUserRequest) returns (CreateUserReply);
}


//types
message Klient {
  int64 id = 1;
  string fname = 2;
  string nname = 3;
}

message Color {
  int32 r = 1;
  int32 g = 2;
  int32 b = 3;
}

message Uhrzeit {
  int32 hour = 1;
  int32 minute = 2;
}

message Datum {
  int32 year = 1;
  int32 month = 2;
  int32 day = 3;
}

message Zeiteintrag {
  Datum dayofentry = 1;
  Uhrzeit anfang = 2;
  Uhrzeit ende = 3;
  int64 taetigkeitid = 4;
  int64 klientid = 5;
  string beschreibung = 6;
  int64 eintragid = 7;
}

message Dokument {
  string name = 1;
  IdObjekt Gruppe = 2;
  repeated IdObjekt Kategorie = 3;
  string author = 4;
  int64 klient = 5;
}

message IdObjekt {
  int64 id = 1;
  string bezeichnung = 2;
}


//messages
message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginReply {
  string error_code = 1;
  string access_token = 2;
  Color darkbg = 3;
  Color lightbg = 4;
  repeated Klient klienten = 5;
  int32 forceResetPass = 6;
  int32 role = 7;
}

message DocumentConfigRequest {

}

message DocumentConfigReply {
  repeated IdObjekt Kategorien = 1;
  repeated IdObjekt Gruppen = 2;
}

message DocumentsRequest {
  int64 klientid = 1;
}

message DocumentsReply {
  repeated Dokument Dokumente = 1;
}

message DocumentRequest {
  Dokument dokument = 1;
}

message DocumentReply {
  bytes file = 1;
}

message DeleteDocumentRequest {
  Dokument dokument = 1;
}

message DeleteDocumentReply {
  
}

message SendDocumentRequest {
  Dokument dokument = 1;
  bytes file = 2;
}

message SendDocumentReply {
  string error_code = 1;
}

message TaetigkeitRequest {
}

message TaetigkeitReply {
  repeated IdObjekt Taetigkeiten = 1;
}

message ZeiteintraegeRequest {
  Datum zeiteintragdatum = 1;
}

message ZeiteintraegeReply {
  repeated Zeiteintrag zeiteintraege = 1;
}

message ZeiteintragRequest {
  Zeiteintrag zeiteintrag = 1;
  int32 operation = 2;
}

message ZeiteintragReply {
  string error_code = 1;
}

message PasswordChangeRequest {
  string oldPassword = 1;
  string newPassword = 2;
}

message PasswordChangeReply {
  string error_code = 1;
}

message CreateUserRequest {
  string loginName = 1;
  string email = 2;
  string fname = 3;
  string lname = 4;
  int32 role = 5;
}

message CreateUserReply {
  string error_code = 1;
}